version: "3"

services:
  cloudservice:
    container_name: cloudservice
    build:
      context: .
    ports:
      - "5050:5050"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  frontend:
      image: "front"
      build: "./front/"
      container_name: "cloudservice-front"
      ports:
        - "8080:8080"
      depends_on:
        - "cloudservice"